In [3]:
import numpy as np

   # 1. zeros ()  array , 2 by 3 Array Creation:
   

In [4]:
arr = np.zeros((2,3))

In [5]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

# 2. empty ()  array

In [6]:
arr1 = np.empty([4,5])    #empy array

In [7]:
arr1     #Checking

array([[1.02493618e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 7.56587583e-307],
       [5.30276956e+180, 1.57076922e-076, 6.98476053e-076,
        4.46470459e-086, 3.35709684e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 4.28081192e-037],
       [4.28080467e-037, 2.21225372e+160, 8.37821971e+169,
        6.15540458e-144, 1.50008929e+248]])

# 3. array creation by Arange arange () 

In [8]:
arr2 = np.arange(1,20, 2)

In [9]:
arr2  # Checking

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# 4. reshape() 

In [10]:
arr2.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

# 5. linspace ()

In [11]:
arr5 = np.linspace(0,10, 5)   # equal gap in between element

In [12]:
arr5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 6. exp()

In [13]:
np.exp(arr5)

array([1.00000000e+00, 1.21824940e+01, 1.48413159e+02, 1.80804241e+03,
       2.20264658e+04])

# 7. sum()

In [14]:
np.sum(arr5)

25.0

# 8. add()

In [15]:
np.add(arr5, [1,2,3,4,5])

array([ 1. ,  4.5,  8. , 11.5, 15. ])

# 9. sqrt()

In [16]:
np.sqrt(arr5)

array([0.        , 1.58113883, 2.23606798, 2.73861279, 3.16227766])

# 10. min()

In [17]:
np.min(arr5)

0.0

# 11. Max()

In [18]:
np.max(arr5)

10.0

# 12. Average()

In [19]:
np.average(arr5)

5.0

# 13. view ()

In [20]:
arr6 = arr5.view()

In [21]:
arr6 is arr5

False

In [22]:
arr6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
arr5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
arr5[0] = 3

In [25]:
arr6

array([ 3. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
arr5

array([ 3. ,  2.5,  5. ,  7.5, 10. ])

# 14. copy()

In [27]:
arr7 = arr5.copy()

In [28]:
arr7 

array([ 3. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
arr7[0] = 20

In [30]:
arr7

array([20. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
arr5

array([ 3. ,  2.5,  5. ,  7.5, 10. ])

# 15. mean()

In [32]:
arr5.mean()

5.6

# 16 all()

In [33]:

arr5.all()


True

# 17 cumprod() 

In [34]:

arr5.cumprod()


array([   3.  ,    7.5 ,   37.5 ,  281.25, 2812.5 ])

# 18 cumsum()

In [234]:
arr5.cumsum()

array([ 3. ,  5.5, 10.5, 18. , 28. ])

# 19 size()

In [36]:
#19
np.size(arr5)

5

# 20 round()

In [235]:

arr5.round()

array([ 3.,  2.,  5.,  8., 10.])

# 21 argmax()

In [38]:


arr5.argmax()

4

# 22. argmin()

In [39]:


arr5.argmin()

1

# 23 ravel()

In [40]:

arr20 = np.array([[2,4,5,6],
                [6,7,7,8]])
arr20


array([[2, 4, 5, 6],
       [6, 7, 7, 8]])

In [41]:
arr20.ravel()

array([2, 4, 5, 6, 6, 7, 7, 8])

# 24 clip()

In [42]:
#24
arr20.clip(5,9)

array([[5, 5, 5, 6],
       [6, 7, 7, 8]])

# 25 argsort()

In [43]:

arr20.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

# 26 true_divide()

In [248]:

np.true_divide([30,40,50],5)


array([ 6.,  8., 10.])

# 27 var() 

In [45]:

arr20

array([[2, 4, 5, 6],
       [6, 7, 7, 8]])

In [46]:
arr20.var()

3.234375

# 28 byteswap()

In [54]:

arr30 = arr20.byteswap()

In [56]:
arr30

array([[ 33554432,  67108864,  83886080, 100663296],
       [100663296, 117440512, 117440512, 134217728]])

# 29 arra_split()

In [55]:

np.array_split(arr20,2)

[array([[2, 4, 5, 6]]), array([[6, 7, 7, 8]])]

# 30. inner()

In [49]:

x = np.array([2,4])
y = np.array([3,5])

In [50]:
np.inner(x,y)

26

# 31 round()

In [82]:

arr35 = np.array([2.43,5.67,76.8,99.32])
np.round(arr35,1)

array([ 2.4,  5.7, 76.8, 99.3])

# 32 around()

In [85]:

np.around(arr35,2)

array([ 2.43,  5.67, 76.8 , 99.32])

# 33 fix()

In [86]:

np.fix(arr35)

array([ 2.,  5., 76., 99.])

# 34 floor()

In [87]:

np.floor(arr35)

array([ 2.,  5., 76., 99.])

# Ceil()

In [89]:

np.ceil(arr35)

array([  3.,   6.,  77., 100.])

# 35 trunc()

In [249]:

np.trunc(arr35)

array([ 2.,  5., 76., 99.])

# 36 rint()

In [250]:

np.rint(arr35)

# 37 lcm()

In [129]:

np.lcm([55,66,7,8,99],2)

array([110,  66,  14,   8, 198])

# 38 gcd()

In [128]:

np.gcd([55,66,7,8,99],3)

array([1, 3, 1, 1, 3])

# 39 clip()

In [242]:

arr35


array([ 2.43,  5.67, 76.8 , 99.32])

In [134]:
np.clip(arr35,5,66)

array([ 5.  ,  5.67, 66.  , 66.  ])

# 40 square()

In [150]:

arr40 = np.square(arr35)
arr40

array([5.9049000e+00, 3.2148900e+01, 5.8982400e+03, 9.8644624e+03])

# 41 absolute() or abs()

In [241]:

np.absolute([-5,-6,6,3])
np.abs([-5,-6,6,3])

array([5, 6, 6, 3])

# 42 remainder()

In [195]:

arr50 = np.array([[30,40],[55,77]])

In [198]:
np.remainder(arr50,3)

array([[0, 1],
       [1, 2]], dtype=int32)

# 43 exp()

In [201]:

np.exp([4,5,6])

array([ 54.59815003, 148.4131591 , 403.42879349])

# 44 exp2()

In [203]:

np.exp2([4,5,6])

array([16., 32., 64.])

# 45 log2()

In [206]:


np.log2([4,5,6])

array([2.        , 2.32192809, 2.5849625 ])

# 46 cross()

In [238]:

x = [3,5,6]
y = [6,8,9]
np.cross(x,y)

array([-3,  9, -6])

# 47 subtract()

In [220]:


np.subtract(x,y)


array([-3, -3, -3])

# 49 ediff1d()

In [224]:

p = np.array([44,5,8,7,88,99])
np.ediff1d(p)

array([-39,   3,  -1,  81,  11])

 # 50 power()

In [232]:

nn = [4,5,6]
aa = [2,4,8]


In [233]:
np.power(nn,aa)

array([     16,     625, 1679616], dtype=int32)